import "server-only"

import fs from "fs"
import path from "path"
import { cache } from "react"
import type { Feed } from "@/components/packages/demo/derivative/runtime"

/**
 * Input and output of `derivative build` for the demo page. changelog.json was
 * generated by the real CLI from CHANGELOG.md and derivative.config.json in
 * content/demos/derivative; the release dates stand in for the git tags.
 */

const DIR = path.join(process.cwd(), "content", "demos", "derivative")

const read = (file: string) => {
  try {
    return fs.readFileSync(path.join(DIR, file), "utf8")
  } catch {
    return null
  }
}

export const getDerivativeDemo = cache(() => {
  const json = read("changelog.json")
  return {
    feed: json ? (JSON.parse(json) as Feed) : null,
    changelog: read("CHANGELOG.md"),
    config: read("derivative.config.json"),
  }
})
