// Copy of the Logarithm live demo (/logarithm/demo). Kept next to the demo
// instead of lib/copy.ts so package pages stay independent of each other.
export const logarithmDemo = {
  seoTitle: "Logarithm live demo: a self-hosted audit log with a ready React view",
  description:
    "Change settings in a sample SaaS admin and watch Logarithm record who changed what, with field-level diffs, redacted secrets and the ready-made React activity view.",
  title: "Logarithm",
  titleSub: "Live demo.",
  intro:
    "This is the settings page of a made-up SaaS app. Every change you make is recorded with the same code as the npm package and shows up in the activity view next to it, the way your customers' admins would see it.",
  isolation:
    "Everything runs in this page and is kept in memory. Nothing you enter is sent anywhere, and a reload starts over.",
  overview: "Logarithm overview",
  docs: "Read the docs",
  pricing: "See Logarithm Pro",
  app: {
    label: "Try it",
    title: "Change something",
    sub: "and see who did what.",
    lede: "Switch the person you act as, edit the project, invite or remove members, rotate the API key. Open Details on an entry to see the field changes. The SMTP password is stored as [redacted], never in clear text.",
    panel: "Acme Cloud · Project settings",
    actingAs: "Acting as",
    project: "Project",
    name: "Project name",
    plan: "Plan",
    visibility: "Visibility",
    private: "Private",
    public: "Public",
    smtpPassword: "SMTP password",
    save: "Save changes",
    saved: "Saved. Nothing changed, so nothing was recorded.",
    members: "Members",
    role: (email: string) => `Role of ${email}`,
    remove: (email: string) => `Remove ${email}`,
    removeLabel: "Remove",
    invite: "Invite by email",
    inviteButton: "Invite",
    invitePlaceholder: "carla@example.ch",
    apiKey: "API key",
    rotate: "Rotate key",
    reset: "Start over",
    activity: "Activity",
    language: "Language of the view",
    feedHint: "<ActivityFeed>: the latest entries as a dashboard widget.",
    lastEvent: "Last recorded event, as stored",
    lastEventHint: "This is the row Logarithm writes to Postgres or SQLite.",
  },
  code: {
    label: "In your app",
    title: "Three pieces",
    sub: "Record, serve, show.",
    lede: "Record events where things change, expose them through a route that checks access and scopes to the tenant, and drop the view into your admin area.",
  },
  closing: {
    label: "Pro",
    title: "When auditors ask",
    sub: "Logarithm Pro has the answers.",
    lede: "Tamper evidence with an HMAC hash chain, retention periods with archiving, GDPR and Swiss FADP erasure and access requests, CSV export for your customers and forwarding to Splunk, Datadog or signed webhooks.",
  },
}
