/** Text of the Summand live demo (/summand/demo). Kept out of lib/copy.ts so package threads do not collide. */
export const summandDemoCopy = {
  seoTitle: "Summand live demo: validate XRechnung, ZUGFeRD and Factur-X in your browser",
  description:
    "Validate your own XRechnung, ZUGFeRD or Factur-X invoice against the official EN 16931 and XRechnung rules in the browser, check a Leitweg-ID, and see the Pro invoice view and batch report.",
  title: "Summand",
  titleSub: "Live demo, free and Pro.",
  intro:
    "The first two sections run the real @sweberdev/summand build in your browser: the XML Schema check, the XPath and Schematron engine with the official CEN and KoSIT rules, the PDF reader and the Leitweg-ID check. The Pro section shows output of the real Pro packages for a few sample invoices.",
  isolation: "Your invoice never leaves your browser. Nothing is uploaded or stored.",
  legal:
    "Summand checks invoices technically against EN 16931 and XRechnung. It is not tax advice.",
  overview: "Summand overview",
  docs: "Read the docs",
  jump: "On this page",
  jumpLinks: [
    { href: "#validate", label: "Validate an invoice" },
    { href: "#leitweg", label: "Leitweg-ID" },
    { href: "#pro", label: "Pro" },
  ],
  loading: "Loading Summand and the rule sets…",
  failed: "Summand could not be loaded. Reload the page to try again.",

  validate: {
    label: "Validate",
    title: "Check an e-invoice against the official rules",
    sub: "EN 16931 and XRechnung.",
    lede: "Drop an XRechnung or ZUGFeRD / Factur-X file, or pick a sample. Summand finds the syntax and profile, checks the XML Schema, applies the matching rule sets and lists every finding with rule, line and XPath.",
    samples: "Samples",
    sampleList: [
      { file: "xrechnung-ubl.xml", label: "XRechnung UBL" },
      { file: "xrechnung-cii.xml", label: "XRechnung CII" },
      { file: "zugferd-en16931.pdf", label: "ZUGFeRD PDF" },
      { file: "broken.xml", label: "Invoice with errors" },
    ],
    drop: "Drop an XML or PDF invoice here, or",
    choose: "choose a file",
    xrechnung: "Always apply the XRechnung rules",
    german: "Messages in German",
    running: "Validating…",
    valid: "Valid",
    invalid: "Invalid",
    validText: "The invoice passes all checked rules.",
    counts: (e: number, w: number, i: number) =>
      `${e} error${e === 1 ? "" : "s"}, ${w} warning${w === 1 ? "" : "s"}, ${i} note${i === 1 ? "" : "s"}`,
    duration: (ms: number) => `checked in ${ms < 10 ? ms.toFixed(1) : Math.round(ms)} ms`,
    profile: "Profile",
    syntax: "Syntax",
    source: "Source",
    ruleSets: "Rule sets",
    schemas: "XML Schema",
    pdf: (name?: string) => `XML embedded in the PDF${name ? ` (${name})` : ""}`,
    xml: "XML file",
    summary: "Invoice",
    summaryFields: {
      number: "Number",
      issueDate: "Issue date",
      seller: "Seller",
      buyer: "Buyer",
      buyerReference: "Buyer reference",
      payable: "Amount due",
      lines: "Lines",
    },
    findings: "Findings",
    rule: "Rule",
    message: "Message",
    where: "Where",
    line: "line",
    json: "Result as JSON",
    tooLarge: "Please use a file under 5 MB for the demo.",
  },

  leitweg: {
    label: "Leitweg-ID",
    title: "Check the address of a German public buyer",
    sub: "ISO 7064 check digits.",
    lede: "German public authorities are addressed by a Leitweg-ID in the buyer reference (BT-10). A typo means the invoice is rejected. Summand checks the structure and the two check digits.",
    input: "Leitweg-ID",
    sample: "04011000-12349-88",
    valid: "Valid Leitweg-ID",
    invalid: "Not a valid Leitweg-ID",
    parts: { coarse: "Coarse address", fine: "Fine address", check: "Check digits" },
    expected: (d: string) => `The check digits for this address would be ${d}.`,
  },

  pro: {
    label: "Pro",
    title: "Read, show and process invoices in bulk",
    sub: "Summand Pro.",
    lede: "Summand Pro turns invoices into typed data, renders them for people, watches your inbox folder and hands valid invoices to DATEV. Below is real output of summand-view and summand-inbox for the sample invoices.",
    view: "summand-view: the invoice with errors as readable HTML, with its validation report",
    viewTitle: "Invoice view rendered by summand-view",
    viewDe: "The ZUGFeRD sample in German",
    viewDeTitle: "German invoice view rendered by summand-view",
    cli: "summand-inbox on a folder of six files",
    report: "The HTML report of the same run",
    reportTitle: "Batch report rendered by summand-inbox",
    audit: "Two lines of the audit log: each line carries the SHA-256 of the file and a chain value over the line before",
    read: "summand-read: one typed object for UBL and CII",
    watch: "summand-inbox watch: checks each file as it arrives and sorts it into valid/, invalid/ and duplicate/",
    datev: "DATEV export of the valid invoices: one booking per VAT rate, ready for your tax advisor to import",
    cta: "Pricing and licences",
  },

  closing: {
    label: "Next step",
    title: "Validate invoices where they arrive",
    sub: "MIT licensed.",
    lede: "Install @sweberdev/summand and call validateInvoice in your upload route, your mail handler or your CI. The getting started guide takes five minutes.",
    cta: "Getting started",
  },
}
