/** Text of the Vector live demo (/vector/demo). Kept out of lib/copy.ts so package threads do not collide. */
export const vectorDemoCopy = {
  seoTitle: "Vector live demo: Standard Webhooks signatures, retries and delivery log in your browser",
  description:
    "Sign and verify a webhook with Standard Webhooks headers, watch Vector retry failing endpoints on a simulated clock with a full delivery log, test its SSRF guard against private addresses, and see what Vector Pro adds.",
  title: "Vector",
  titleSub: "Live demo, free and Pro.",
  intro:
    "The first three sections run the real @sweberdev/vector build in your browser: signing and verification, the sender with its retry schedule and delivery log, and the SSRF guard. The receivers in the delivery simulator are simulated, nothing is sent over the network.",
  isolation:
    "Nothing you type leaves your browser. Secrets are generated with Web Crypto on this page and are gone when you reload it.",
  overview: "Vector overview",
  docs: "Read the docs",
  receiving: "Verify webhooks",
  jump: "On this page",
  jumpLinks: [
    { href: "#signing", label: "Sign and verify" },
    { href: "#delivery", label: "Delivery simulator" },
    { href: "#ssrf", label: "SSRF guard" },
    { href: "#pro", label: "Pro" },
  ],
  loading: "Loading Vector…",
  failed: "Vector could not be loaded. Reload the page to try again.",

  signing: {
    label: "Sign and verify",
    title: "Three headers, one HMAC",
    sub: "Standard Webhooks, Svix compatible.",
    lede: "Vector signs the message id, the timestamp and the body with HMAC-SHA256 and sends the result in webhook-id, webhook-timestamp and webhook-signature. Any Standard Webhooks or Svix library can verify it. Change the body, the secret or the clock on the receiving side and watch verification fail with the error code your handler would see.",
    sender: "Sender",
    receiver: "Receiver",
    secret: "Endpoint secret",
    newSecret: "Generate a new secret",
    body: "Request body (JSON)",
    resign: "Sign again now",
    headers: "Headers Vector sends",
    rxBody: "Body as received",
    rxSecret: "Secret the receiver uses",
    rxTimestamp: "webhook-timestamp as received",
    clock: "Receiver clock",
    clocks: [
      { value: 0, label: "In sync" },
      { value: 240, label: "4 minutes ahead (within tolerance)" },
      { value: 600, label: "10 minutes ahead (replayed later)" },
      { value: -600, label: "10 minutes behind" },
    ],
    tamper: "Tamper with the body",
    wrongSecret: "Use a different secret",
    reset: "Receive exactly what was sent",
    valid: "Valid: signature matches, timestamp within five minutes.",
    invalid: "Rejected",
    verifyCode: "On the receiving side",
    codes: {
      missing_headers: "A webhook header is missing.",
      invalid_timestamp: "The timestamp is not a number.",
      timestamp_too_old: "The timestamp is more than five minutes old. This stops replays of captured requests.",
      timestamp_too_new: "The timestamp is more than five minutes in the future.",
      no_matching_signature: "No signature matches: the body, the id, the timestamp or the secret differ from what was signed.",
      invalid_payload: "The signature matches, but the body is not valid JSON.",
    } as Record<string, string>,
  },

  delivery: {
    label: "Delivery simulator",
    title: "Retries you can watch",
    sub: "Real sender, simulated receivers, fake clock.",
    lede: "This is createVector with a memory store, three endpoints of the tenant acme and a fetch that answers the way you set each receiver. The clock only moves when you move it, and after every step the worker runs one process() pass, so you can follow each attempt, the backoff and the automatic disabling of a dead endpoint.",
    schedule:
      "The demo uses a short retry schedule: 10 s, 30 s, 1 min and 2 min, so five attempts, and disables an endpoint after three failed deliveries in a row. The default is eight attempts over about 27 hours and ten failed deliveries. Timeouts are set to 1.5 s of real time.",
    endpoints: "Endpoints of tenant acme",
    behaviour: "Receiver answers",
    behaviours: {
      healthy: "200 OK",
      failing: "500 Internal Server Error",
      limited: "429 with Retry-After: 90",
      slow: "Nothing (times out)",
      gone: "410 Gone",
    },
    filter: "Event types",
    allEvents: "all",
    enabled: "Enabled",
    disabled: "Disabled",
    streak: (n: number) => `${n} failed ${n === 1 ? "delivery" : "deliveries"} in a row`,
    enable: "Enable again",
    test: "Send test event",
    send: "Send event",
    eventType: "Event type",
    clock: "Clock",
    elapsed: (s: string) => `${s} since the start of the demo`,
    advance: "Advance the clock",
    advanceBy: [
      { seconds: 10, label: "+10 s" },
      { seconds: 60, label: "+1 min" },
      { seconds: 300, label: "+5 min" },
    ],
    next: "Jump to the next attempt",
    noneDue: "Nothing is waiting for a retry.",
    reset: "Start over",
    working: "Delivering…",
    log: "Delivery log",
    empty: "No messages yet. Send an event to start.",
    noSubscriber: "No endpoint of this tenant subscribes to this event type, so nothing is delivered.",
    senderCode: "The sender in this demo",
    message: "Message",
    to: "to",
    status: { pending: "Pending", succeeded: "Delivered", failed: "Failed", cancelled: "Cancelled" },
    attemptsOf: (n: number, max: number) => `${n} of ${max} attempts`,
    nextIn: (s: string) => `next attempt in ${s}`,
    dueNow: "next attempt due now",
    attempts: "Attempts",
    attemptAt: (s: string) => `at ${s}`,
    retry: "Retry",
    resend: "Resend message",
    lastRequest: "Last request a receiver got",
    noRequest: "No request yet.",
    announceDisabled: (url: string, reason: string) => `Endpoint ${url} was disabled: ${reason}.`,
    announcePass: (r: { succeeded: number; retrying: number; failed: number }) =>
      `Worker pass: ${r.succeeded} delivered, ${r.retrying} scheduled for a retry, ${r.failed} failed.`,
  },

  ssrf: {
    label: "SSRF guard",
    title: "Customer URLs never reach your network",
    sub: "Checked on create and before every attempt.",
    lede: "Endpoint URLs come from your customers. Vector refuses localhost, private and link-local networks (including the cloud metadata address 169.254.169.254), plain http and credentials in the URL, unless you allow them. On Node.js it also resolves the host name and checks every address, so a DNS record pointing inside your network is caught too.",
    input: "Endpoint URL",
    examples: "Examples",
    allowed: "Allowed",
    refused: "Refused",
    dnsNote:
      "Browsers have no DNS lookup, so in this demo host names are resolved from a small table: intranet.acme.example points to 10.0.0.12, every other name to a public address.",
    private: (ip: string, isPrivate: boolean) =>
      `isPrivateAddress("${ip}") is ${isPrivate ? "true" : "false"}.`,
  },

  pro: {
    label: "Pro",
    title: "The portal, the catalog and the night shift",
    sub: "Vector Pro.",
    lede: "The free package sends, retries and logs. Vector Pro adds the parts you would otherwise build next: an embeddable portal where your customers manage their own endpoints, a typed event catalog that validates payloads and generates docs, and operations tooling for alerts, recovery after outages, metrics and retention. Vector Pro is not on sale yet; the snippets show how it plugs in.",
    portal: "Customer portal: one route handler, scoped to the tenant",
    portalUi: "And the React components on your settings page",
    portalNote:
      "The handler serves endpoints, secrets, the message log, retries and test events for exactly one tenant, the one your authorize function returns. The components talk to it and bring their own styles.",
    catalog: "Event catalog",
    catalogNote:
      "Every event type gets a schema (Zod, Valibot, ArkType or any Standard Schema library). Payloads are checked before they are sent, and the same catalog generates Markdown docs, an AsyncAPI 3 file and TypeScript types for your customers.",
    ops: "vector-ops sends alerts to Slack, email or a webhook when an endpoint keeps failing, replays everything that failed during an outage in one command, writes a health report, exposes Prometheus metrics and deletes old log data on a schedule.",
    cta: "See Vector Pro",
    waitlist: "Join the waitlist",
  },

  closing: {
    label: "Next",
    title: "Send your first webhook",
    sub: "MIT, free.",
    lede: "Install @sweberdev/vector, create an endpoint for a customer, call send() and start the worker. The getting started guide covers PostgreSQL, serverless and the receiving side.",
    cta: "Get started",
  },
}
