/**
 * Strings of the Suchstring-Generator (tool, demo and paywall page).
 * German, Swiss orthography, informal "du". A copywriter pass happens later:
 * change wording here, not in the components.
 */
import type { Block, LintSeverity, NoticeSeverity } from "@/lib/physio/search-string/types"

export const ssCopy = {
  name: "Suchstring-Generator",
  metaTitle: "Suchstring-Generator für PubMed und Cochrane Library",
  metaDescription:
    "Baut aus deiner PICO-Frage oder deinem Patientenfall einen Suchstring für PubMed und die Cochrane Library mit Schlagworten (MeSH), Stichworten, Klammern und Trunkierung. Regelbasiert, ohne KI. Sprache und Zeitraum stellst du in der Cochrane Library selbst ein. Deine Fragestellung bleibt auf deinem Gerät.",

  hero: {
    title: "Suchstring-Generator",
    sub: "Von der PICO-Frage zum Suchstring für PubMed und die Cochrane Library.",
    lede: "Fall einfügen, Suchstring kopieren, bei Bedarf anpassen.",
    demoBadge: "Demo",
    demoLede: "Probier den Generator an einem festen Beispielfall aus.",
  },

  privacyShort: "Dein Fall bleibt auf deinem Gerät.",
  privacy:
    "Deine Fragestellung bleibt auf deinem Gerät. Das Tool lädt nur Teile eines öffentlichen MeSH-Wörterbuchs von physio.sweber.dev nach; abgefragt wird dabei ein Dateiname wie «terms/lo.json», nie dein Text. Die Trefferzählung ist optional und schickt nur den fertigen Suchstring an PubMed (NCBI).",
  attribution: {
    source: "MeSH: U.S. National Library of Medicine · Deutsche Bezeichnungen: Wikidata (CC0)",
    version: (version: string, descriptors: number, german: number) =>
      `Wörterbuch: MeSH ${version}, ${descriptors.toLocaleString("de-CH")} Schlagworte, davon ${german.toLocaleString("de-CH")} mit deutschen Bezeichnungen.`,
    loading: "Wörterbuch wird geladen",
  },
  glossary: [
    { term: "Suchkomponente", text: "ein Baustein deiner Frage, zum Beispiel «Rückenschmerzen». Im String ist das eine Klammer, in der die Begriffe mit OR verknüpft sind." },
    { term: "Stichwort", text: "ein Freitext-Begriff, den PubMed in Titel und Abstract sucht ([tiab]). In der Cochrane Library schreibst du ihn mit :ti,ab,kw." },
    { term: "Schlagwort", text: "ein MeSH-Term aus dem kontrollierten Vokabular von PubMed ([Mesh]). In der Cochrane Library schreibst du ihn als [mh …]." },
  ],

  draftNote: {
    title: "Das ist ein Entwurf.",
    body: "Geh Begriffe und Schlagworte durch und schau dir die Trefferliste an, bevor du den String in einer Arbeit verwendest. Das Tool arbeitet mit festen Regeln, dem MeSH-Wörterbuch und einer eigenen Begriffstabelle. Wie es deutsche Wörter den Schlagworten zuordnet, ist fachlich noch nicht geprüft.",
  },

  tabs: { generate: "Suchstring erstellen", lint: "Eigenen String prüfen", label: "Werkzeug" },

  question: {
    exampleLabel: "Beispiel",
    examplePlaceholder: "Beispiel wählen",
    textLabel: "Fall oder Fragestellung einfügen",
    textLabelDemo: "Fall",
    textPlaceholder: "Wie wirkt Krafttraining auf die Schmerzen bei älteren Menschen mit Kniearthrose?",
    textHint:
      "Tipp: «bei» leitet die Population ein, «im Vergleich zu» den Vergleich, «auf die» das Outcome. Zeilen mit «P:», «I:», «C:», «O:» oder «Population:», «Intervention:», «Outcome:» haben Vorrang. Schreib Hauptwörter gross, dann erkennt das Tool sie sicherer. Arbeitsaufträge wie «Formulieren Sie …» überliest das Tool.",
    analysing: "Wörterbuch wird geladen und Fall ausgewertet",
    picoHint: "Was du hier einträgst, landet fix im passenden Block. Die Felder gelten, sobald du den Suchstring neu erstellst.",
    pico: {
      population: { label: "Population (P)", placeholder: "Wer? Person oder Erkrankung" },
      intervention: { label: "Intervention (I)", placeholder: "Was wird gemacht?" },
      comparison: { label: "Vergleich (C)", placeholder: "Womit wird verglichen?" },
      outcome: { label: "Outcome (O)", placeholder: "Was wird gemessen?" },
      studyType: { label: "Studientyp", placeholder: "zum Beispiel RCT" },
    },
    submit: "Suchstring erstellen",
    submitting: "Wird ausgewertet",
    resubmit: "Mit diesen Feldern neu erstellen",
    emptyError: "Schreib zuerst einen Fall oder eine Fragestellung, oder füll mindestens ein PICO-Feld aus.",
    failError: "Der Fall liess sich nicht auswerten. Kürze den Text oder füll die PICO-Felder direkt aus.",
    lockedBody: "In der Demo wählst du nur Beispiele. Eigene Fälle gibt es mit dem Abo.",
    editedHint: "«Suchstring erstellen» setzt deine Änderungen an den Komponenten zurück.",
    created: "Suchstring erstellt.",
  },

  /** The areas under the result, folded by default. Status lines tell whether it is worth opening one. */
  sections: {
    heading: "Anpassen",
    hint: "Alles optional. Was du hier änderst, steht sofort im String oben.",
    current: "Aktueller Schritt",
    concepts: {
      title: "Suchkomponenten bearbeiten",
      status: (n: number, withoutMesh: number, unused: number) => {
        const parts = [`${n} ${n === 1 ? "Komponente" : "Komponenten"}`]
        if (withoutMesh) parts.push(`${withoutMesh} ohne Schlagwort`)
        if (unused) parts.push(`${unused} ${unused === 1 ? "Wort" : "Wörter"} nicht übernommen`)
        return parts.join(", ")
      },
      none: "noch keine Komponente",
    },
    pico: {
      title: "PICO-Felder",
      status: (filled: number, total: number) => (filled ? `${filled} von ${total} ausgefüllt` : "nicht ausgefüllt"),
      statusLocked: (filled: number, total: number) => (filled ? `${filled} von ${total} aus dem Beispiel` : "im Beispiel nicht ausgefüllt"),
    },
    filters: {
      title: "Filter",
      none: "keine Filter",
      active: (n: number) => `${n} Filter aktiv`,
      suggestions: (n: number) => `${n} ${n === 1 ? "Vorschlag" : "Vorschläge"} aus deinem Fall`,
      names: { language: "Sprache", years: "Zeitraum", studyTypes: "Studientyp", humans: "nur Menschen", age: "Alter", sex: "Geschlecht" },
    },
    mesh: { title: "MeSH-Wörterbuch durchsuchen", status: "Schlagwort auf Deutsch oder Englisch suchen" },
    table: {
      title: "Tabelle für die Übung (RefHunter)",
      status: (rows: number) => `${rows} ${rows === 1 ? "Zeile" : "Zeilen"}: Komponente, Stichworte, Schlagworte`,
    },
    diff: {
      title: "Unterschiede zwischen Datenbanken",
      status: (names: string) => names,
    },
    export: { title: "Export (.txt / .json)", status: "den String als Datei speichern" },
  },

  concepts: {
    hint: "Schau nach, ob das Tool deine Frage richtig verstanden hat. Entferne, verschiebe oder ergänze Komponenten, bevor du den String übernimmst.",
    emptyTitle: "Noch keine Suchkomponente.",
    emptyBody: "Erstelle den Suchstring oben oder füge unten eine Komponente hinzu.",
    detectedFrom: "erkannt aus",
    custom: "eigene Komponente",
    noMesh: "Kein Schlagwort hinterlegt. Diese Komponente wird nur über Stichworte gesucht.",
    blocks: {
      population: { title: "Population", sub: "Wer oder welche Erkrankung?" },
      intervention: { title: "Intervention", sub: "Was wird gemacht?" },
      comparison: { title: "Vergleich", sub: "Womit wird verglichen?" },
      outcome: { title: "Outcome", sub: "Was wird gemessen?" },
    } satisfies Record<Block, { title: string; sub: string }>,
    blockInclude: "Im Suchstring",
    blockExcluded: "Dieser Block steht nicht im String.",
    comparisonNote: "Ein Vergleich im String schränkt die Treffer meist zu stark ein. Darum ist dieser Block standardmässig aus.",
    emptyBlock: "Keine Komponente in diesem Block.",
    schlagworte: "Schlagworte (MeSH)",
    stichworte: "Stichworte",
    explodeOn: "mit Unterbegriffen",
    explodeOff: "ohne Unterbegriffe",
    explodeHelp: "Mit Unterbegriffen findet [Mesh] auch alle engeren MeSH-Terms darunter. Ohne ([Mesh:NoExp]) nur genau diesen einen.",
    removeConcept: "Komponente entfernen",
    removeConceptButton: "Entfernen",
    allMeshRemoved: "Alle Schlagworte sind entfernt.",
    allTextRemoved: "Alle Stichworte sind entfernt.",
    moveTo: "Block",
    removeTerm: "entfernen",
    restore: "Wiederherstellen",
    removedTerms: "Entfernte Begriffe",
    addTermLabel: "Stichwort ergänzen",
    addTermPlaceholder: "englisches Wort oder Phrase",
    addTermButton: "Hinzufügen",
    addTermHint: "PubMed sucht auf Englisch. Mit * trunkierst du: exercis* findet exercise, exercises und exercising.",
    addConceptHeading: "Komponente ergänzen",
    addFromList: "Aus der Begriffstabelle",
    addFromListPlaceholder: "Komponente wählen",
    addFromListButton: "Komponente hinzufügen",
    addCustomLabel: "Eigene Komponente",
    addCustomPlaceholder: "englisches Stichwort",
    addCustomButton: "Eigene Komponente hinzufügen",
    categories: {
      population: "Population und Erkrankung",
      setting: "Umfeld",
      intervention: "Intervention",
      comparison: "Vergleich",
      outcome: "Outcome",
      studytype: "Studientyp",
    },
    candidatesHeading: "Nicht übernommene Wörter",
    candidatesHint:
      "Diese Wörter hat das Tool nicht als Komponente aufgenommen. Bei manchen kennt das MeSH-Wörterbuch einen Begriff, der aber zu allgemein ist, um ihn ungefragt zu übernehmen. Alle anderen kannst du als Stichwort übernehmen, dann aber auf Englisch, weil PubMed so sucht.",
    candidateSuggestion: "Im Wörterbuch",
    candidateAddSuggestion: "Als Komponente übernehmen",
    candidateAdd: "Als Stichwort übernehmen",
    candidateDismiss: "Verwerfen",
    candidateBlock: "Block",
    notices: "Hinweise zur Auswertung",
    meshTitle: "Definition und deutsche Bezeichnungen",
    englishName: "Englisch",
    scopeNote: "Definition (englisch)",
    germanNames: "Deutsche Bezeichnungen",
    noGerman: "Keine deutsche Bezeichnung im Wörterbuch.",
    alternativesHeading: "Anderes Schlagwort wählen",
    alternativesHint: "Das Wort kann mehrere Schlagworte meinen. Das Tool hat das für Physiotherapie naheliegendste gewählt. Passt ein anderes besser, schalte um.",
    alternativesUse: "Dieses nehmen",
    moreSynonyms: "Weitere Synonyme aus MeSH",
    moreSynonymsHint: "Ein Klick nimmt das Synonym als Stichwort auf.",
    truncOn: "mit *",
    truncOff: "ohne *",
    truncHelp: "Stern anhängen: exercise* findet auch exercises und exercising. Das hilft nur, wenn der Wortanfang eindeutig ist.",
    truncLabel: "Trunkierung",
    tree: {
      open: "Breiter oder enger",
      close: "Schliessen",
      heading: "Breiter oder enger suchen",
      hint: "Ein breiteres Schlagwort findet mehr, ein engeres weniger. Mit «mit Unterbegriffen» sucht [Mesh] ohnehin alles darunter.",
      broader: "Breiter",
      narrower: "Enger",
      noBroader: "Das ist schon der oberste Begriff in diesem Zweig.",
      noNarrower: "Keine engeren Begriffe.",
      use: "Ersetzen durch",
      loading: "Wörterbuch wird geladen",
      failed: "Der Begriff liess sich im Wörterbuch nicht finden.",
    },
  },

  mesh: {
    heading: "MeSH-Wörterbuch durchsuchen",
    hint: "Such ein Schlagwort auf Deutsch oder Englisch, lies die Definition und nimm es als Komponente auf. Ab drei Buchstaben erscheinen Vorschläge. Deutsche Bezeichnungen gibt es für etwa die Hälfte der Schlagworte; findest du nichts, probier den englischen Namen.",
    label: "Schlagwort suchen",
    placeholder: "zum Beispiel Rückenschmerzen oder low back pain",
    loading: "Wörterbuch wird geladen",
    minChars: "Tippe mindestens drei Buchstaben.",
    noResults: "Keine Treffer. Probier den englischen Namen oder einen kürzeren Wortanfang.",
    failed: "Das Wörterbuch ist gerade nicht erreichbar. Versuch es später noch einmal.",
    results: (n: number) => `${n} ${n === 1 ? "Vorschlag" : "Vorschläge"}`,
    english: "Englisch",
    german: "Deutsch",
    noGerman: "keine deutsche Bezeichnung",
    category: "Bereich",
    treeNumbers: "Baumnummer",
    scopeNote: "Definition (englisch)",
    noScopeNote: "Keine Definition im Wörterbuch.",
    broader: "Breiter",
    narrower: "Enger",
    noBroader: "oberster Begriff",
    noNarrower: "keine engeren Begriffe",
    add: "Zu Suchkomponente hinzufügen",
    addBlock: "Block",
    added: "Hinzugefügt. Du findest die Komponente oben im gewählten Block.",
    alreadyThere: "Diese Komponente gibt es schon.",
    categories: {
      A: "Körperregion und Anatomie",
      B: "Lebewesen",
      C: "Krankheit oder Beschwerde",
      D: "Medikament oder Substanz",
      E: "Verfahren und Geräte",
      F: "Psyche und Verhalten",
      G: "Körperfunktion und Vorgänge",
      H: "Fachgebiet",
      I: "Gesellschaft und Bildung",
      J: "Technik und Ernährung",
      L: "Information",
      M: "Personengruppe",
      N: "Gesundheitswesen",
      V: "Publikationstyp",
      Z: "Ort",
    } as Record<string, string>,
  },

  database: {
    legend: "Datenbank",
    atLeastOne: "Mindestens eine Datenbank bleibt gewählt.",
    cochraneFilters:
      "Für die Cochrane Library stehen Sprache, Zeitraum, Studientyp und «nur Menschen» nicht im String, weil sich das dort nicht zuverlässig als Syntax schreiben lässt. Im Ergebnis steht dann, was du unter «Search limits» einstellst. Alter und Geschlecht schreibt das Tool als MeSH-Check-Tag.",
    filtersHint: "Alle Filter sind optional.",
    language: "Sprache",
    languageAny: "alle Sprachen",
    years: "Erscheinungsjahr",
    yearFrom: "von",
    yearTo: "bis",
    yearPlaceholder: "Jahr",
    studyTypes: "Studientyp",
    studyTypeLabels: {
      rct: "Randomisierte kontrollierte Studie",
      "systematic-review": "Systematische Übersichtsarbeit",
      "meta-analysis": "Metaanalyse",
    },
    humans: "Nur Studien am Menschen",
    humansHint: "Schliesst reine Tierstudien aus. Gilt für PubMed; die Cochrane Library hat dafür keinen Filter.",
    caseHeading: "Vorschläge aus deinem Fall",
    caseHint:
      "Alter und Geschlecht stehen oft im Fall. Als Filter schränken sie die Treffer stark ein, weil PubMed beides nicht bei jeder Studie verschlagwortet. Darum sind die Vorschläge aus. Schalte sie nur ein, wenn die Frage wirklich auf diese Gruppe zielt.",
    fromCase: (evidence: string) => `aus «${evidence}»`,
    ageLabels: {
      "Infant, Newborn": "Neugeborene",
      Infant: "Säuglinge (bis 23 Monate)",
      "Child, Preschool": "Vorschulkinder (2 bis 5 Jahre)",
      Child: "Kinder (6 bis 12 Jahre)",
      Adolescent: "Jugendliche (13 bis 18 Jahre)",
      "Young Adult": "Junge Erwachsene (19 bis 24 Jahre)",
      Adult: "Erwachsene (19 bis 44 Jahre)",
      "Middle Aged": "Mittleres Alter (45 bis 64 Jahre)",
      Aged: "Ältere (65 bis 79 Jahre)",
      "Aged, 80 and over": "Hochbetagte (ab 80 Jahren)",
    } as Record<string, string>,
    sexLabels: { Male: "Männlich", Female: "Weiblich" } as Record<string, string>,
  },

  result: {
    heading: "Dein Suchstring",
    created: "Suchstring erstellt",
    stringLabel: "Suchstring für PubMed",
    draftShort: "Entwurf. Prüfe Begriffe und Trefferzahl, bevor du ihn verwendest.",
    draftMore: "mehr",
    draftLess: "weniger",
    componentsLabel: "Erkannte Suchkomponenten",
    blockLetters: { population: "P", intervention: "I", comparison: "C", outcome: "O" } as Record<Block, string>,
    blockNames: { population: "Population", intervention: "Intervention", comparison: "Vergleich", outcome: "Outcome" } as Record<Block, string>,
    withMesh: "mit Schlagwort (MeSH)",
    meshMark: "MeSH",
    notInString: "nicht im String",
    noneInBlock: "keine",
    hints: (n: number, warnings: number) =>
      `${n} ${n === 1 ? "Hinweis" : "Hinweise"}${warnings ? `, davon ${warnings} ${warnings === 1 ? "Warnung" : "Warnungen"}` : ""}`,
    hintsShow: "anzeigen",
    hintsHide: "ausblenden",
    managerTitle: "Search Manager (zeilenweise)",
    openIn: (db: string) => `In ${db} öffnen`,
    noCount: (db: string) => `Für ${db} gibt es hier keine Trefferzählung: Die Datenbank ist lizenziert und hat keine offene Schnittstelle. Die Trefferzahl siehst du in der Datenbank selbst.`,
    managerTitleFor: (db: string) => `${db}, zeilenweise`,
    managerStatus: (n: number) => `${n} ${n === 1 ? "Zeile" : "Zeilen"}`,
    downloadLines: "Zeilen als .txt",
    exportFor: (db: string) => `Export ${db}`,
    exportLinesTxt: "Als .txt, zeilenweise",
    exportLinesJson: "Als .json, zeilenweise",
    stringLabelFor: (db: string) => `Suchstring für ${db}`,
    format: {
      label: "Format",
      single: "Eine Zeile",
      manager: "Search Manager (zeilenweise)",
    },
    copyLines: "Zeilen kopieren",
    linesCopied: "Zeilen kopiert",
    cochraneSingleHint:
      "Füge den String im «Search manager» der Cochrane Library in eine Suchzeile ein. Eine Zeile versteht Klammern, AND, OR, NOT, [mh …] und Feldcodes.",
    cochraneManagerHint:
      "Ein Begriff pro Zeile, dann je Suchkomponente eine OR-Zeile und am Ende eine AND-Zeile. So siehst du die Trefferzahl jedes Begriffs. Lege die Zeilen der Reihe nach im Search Manager an, ab #1: Die Nummern vergibt die Cochrane Library selbst. Ob mehrzeilig eingefügter Text dort automatisch auf Zeilen verteilt wird, haben wir nicht geprüft; wenn nicht, füge Zeile für Zeile ein. Die Nummern stehen im Download.",
    cochraneOpen: "In Cochrane Library öffnen",
    cochraneOpenHint: "Öffnet den Search Manager. Die Cochrane Library nimmt über einen Link keinen String entgegen, du fügst ihn selbst ein.",
    cochraneNoCount:
      "Eine Trefferzählung gibt es hier nur für PubMed. Für die Cochrane Library kennen wir keine offene Schnittstelle, die ein Browser ohne Anmeldung ansprechen darf. Der Search Manager zeigt dir die Trefferzahl jeder Zeile selbst.",
    limitsHeading: "Das stellst du in der Cochrane Library selbst ein",
    limitsHint: "Diese Filter lassen sich dort nicht zuverlässig als Syntax schreiben. Sie stehen darum nicht im String.",
    lineKinds: { term: "Begriff", component: "Suchkomponente", filter: "Filter", final: "Alles verknüpft" },
    diff: {
      heading: "So steht jede Suchkomponente in PubMed und in der Cochrane Library",
      intro:
        "Dieselben Begriffe, zweimal geschrieben. Gleich bleiben die Logik (OR innerhalb, AND zwischen den Suchkomponenten) und die Klammern.",
      component: "Suchkomponente",
      pubmed: "PubMed",
      cochrane: "Cochrane Library",
      points: [
        "Schlagwort: [Mesh] wird zu [mh …]. Ohne Unterbegriffe schreibst du in PubMed [Mesh:NoExp], in der Cochrane Library ein ^ vor das Schlagwort.",
        "Stichwort: [tiab] wird zu :ti,ab,kw. Der Feldcode steht hinter dem Begriff, und die Cochrane Library sucht zusätzlich in den Schlüsselwörtern.",
        "Trunkierung: PubMed erlaubt * in Anführungszeichen, die Cochrane Library nicht. Dort wird aus «back exercise*» der Ausdruck (back NEXT exercise*).",
        "Filter: Sprache, Zeitraum und Studientyp stehen in PubMed im String, in der Cochrane Library stellst du sie selbst unter «Search limits» ein.",
      ],
    },
    empty: "Noch kein Suchstring. Dafür braucht es mindestens eine Suchkomponente mit einem aktiven Begriff.",
    copy: "Kopieren",
    copied: "Kopiert",
    copyFailed: "Kopieren hat nicht geklappt. Markiere den String und kopiere ihn von Hand.",
    downloadTxt: "Als .txt",
    downloadJson: "Als .json",
    stats: (components: number, terms: number) =>
      `${components} ${components === 1 ? "Suchkomponente" : "Suchkomponenten"}, ${terms} ${terms === 1 ? "Begriff" : "Begriffe"}`,
    noticesHeading: "Hinweise zur Auswertung",
    tableHeading: "Suchkomponenten im Überblick",
    tableCols: { component: "Suchkomponente", keywords: "Stichworte", subjectHeadings: "Schlagworte (MeSH)", syntax: "Schreibweise" },
    none: "keine",
    legend: "So liest du den String: Schlagworte mit [Mesh] sind umrandet, Stichworte mit [tiab] sucht PubMed in Titel und Abstract, AND und OR sind grau.",
    legendCochrane:
      "So liest du den String: Schlagworte mit [mh …] sind umrandet, Stichworte mit :ti,ab,kw sucht die Cochrane Library in Titel, Abstract und Schlüsselwörtern, AND, OR und NEXT sind grau.",
  },

  pubmed: {
    heading: "Treffer in PubMed",
    hint: "Optional. Zählt die Treffer jeder Suchkomponente und des ganzen Strings, damit du siehst, welche Komponente die Suche zu stark einschränkt.",
    privacy: "Dafür sendet dein Browser den Suchstring (nicht deine Fragestellung) an PubMed beim US-amerikanischen NCBI.",
    count: "Treffer in PubMed zählen",
    recount: "Noch einmal zählen",
    counting: (done: number, total: number) => `Zähle … (${done} von ${total})`,
    cancel: "Abbrechen",
    cancelled: "Abgebrochen. Die bisherigen Zahlen stehen unten.",
    open: "In PubMed öffnen",
    colComponent: "Suchkomponente",
    colHits: "Treffer",
    total: "Ganzer String",
    pending: "ausstehend",
    failedRow: "Fehler",
    errors: {
      rate: "PubMed hat die Anfragen vorübergehend begrenzt. Warte eine Minute und zähle noch einmal.",
      network: "PubMed ist von deinem Browser aus gerade nicht erreichbar. Prüfe die Verbindung oder öffne den String direkt in PubMed.",
      query: "PubMed hat den String nicht verstanden. Öffne ihn in PubMed, dort steht, was nicht stimmt.",
      other: "Die Zählung hat nicht geklappt. Öffne den String direkt in PubMed.",
    },
    zeroTotal:
      "Der ganze String findet nichts. Schau in der Tabelle, welche Komponente die wenigsten Treffer hat, und lockere dort zuerst. Was meist hilft: eine Komponente rausnehmen (drei bis vier reichen in der Regel), den String einmal ohne den Block Population probieren, ein enges Schlagwort über «Breiter oder enger» durch ein breiteres ersetzen, und die Trunkierung prüfen: Ein Stichwort ohne * findet nur genau diese Wortform.",
    fewTotal:
      "Der ganze String findet nur wenige Treffer. Lockere zuerst die Komponente mit den wenigsten Treffern: ein breiteres Schlagwort, «mit Unterbegriffen» einschalten oder ein Synonym mehr als Stichwort.",
    manyTotal:
      "Der ganze String findet sehr viele Treffer. Eine engere Population, ein konkretes Outcome oder ein Studientyp-Filter grenzt ein.",
    number: (n: number) => n.toLocaleString("de-CH"),
  },

  severity: {
    info: "Hinweis",
    warning: "Warnung",
    error: "Fehler",
  } satisfies Record<NoticeSeverity | LintSeverity, string>,

  lint: {
    heading: "Eigenen String prüfen",
    hint: "Das Tool erkennt die Syntax, markiert typische Fehler und korrigiert, wo es geht.",
    check: "Prüfen",
    checkAgain: "Erneut prüfen",
    moreOptions: "Mehr Optionen",
    moreOptionsStatus: (syntax: string) => `Syntax: ${syntax}. Umwandeln für andere Datenbanken.`,
    marked: "Markierte Stellen im String",
    markedStatus: "den String mit Markierungen lesen",
    resultsLabel: "Ergebnis der Prüfung",
    syntax: {
      label: "Syntax",
      auto: "Automatisch",
      pubmed: "PubMed",
      cochrane: "Cochrane Library",
      detected: (name: string) => `Erkannt: ${name}`,
    },
    convert: {
      toCochrane: "In Cochrane-Syntax umwandeln",
      toPubmed: "In PubMed-Syntax umwandeln",
      exampleToCochrane: "Korrigiertes Beispiel in Cochrane-Syntax zeigen",
      converted: "Umgewandelt. Geh das Ergebnis durch, bevor du es verwendest.",
      nothing: "Hier gab es nichts umzuwandeln.",
      appliedHeading: "Das hat das Tool gemacht",
      unsafeHeading: "Nicht umgewandelt, das prüfst du selbst",
      unsafeHint: "Diese Teile sind unverändert im String geblieben, weil es keine sichere Entsprechung gibt. Raten tut das Tool nicht.",
    },
    inputLabel: "Suchstring einfügen",
    inputPlaceholder: '("back pain"[tiab] OR "Back Pain"[Mesh]) AND ...',
    lockedBody: "In der Demo prüfst du nur den Beispielstring. Eigene Strings gibt es mit dem Abo.",
    insertExample: "Beispielstring einfügen",
    resetExample: "Beispielstring zurücksetzen",
    clear: "Leeren",
    undo: "Rückgängig",
    markedHeading: "Markierte Stellen",
    emptyTitle: "Noch kein String.",
    emptyBody: "Füge einen Suchstring ein und klick auf «Prüfen».",
    notChecked: "Klick auf «Prüfen», dann siehst du hier, was das Tool findet. Danach läuft die Prüfung beim Tippen mit.",
    cleanTitle: "Nichts gefunden.",
    cleanBody: "Die Syntax stimmt. Ob die Begriffe zu deiner Frage passen, kann das Tool nicht beurteilen, das bleibt bei dir.",
    summary: (errors: number, warnings: number, infos: number) => {
      const parts: string[] = []
      if (errors) parts.push(`${errors} Fehler`)
      if (warnings) parts.push(`${warnings} ${warnings === 1 ? "Warnung" : "Warnungen"}`)
      if (infos) parts.push(`${infos} ${infos === 1 ? "Hinweis" : "Hinweise"}`)
      return parts.join(", ")
    },
    goTo: "Zur Stelle",
    fix: "Korrigieren",
    fixAll: "Alles automatisch korrigieren",
    fixAllDone: (n: number) => `${n} ${n === 1 ? "Korrektur" : "Korrekturen"} angewendet.`,
    fixAllNone: "Hier gibt es nichts, was sich automatisch korrigieren lässt.",
    at: "Stelle",
    moreSpots: (n: number) => `und ${n} weitere ${n === 1 ? "Stelle" : "Stellen"}`,
  },

  demo: {
    ctaHeading: "Eigene Fragen auswerten",
    ctaBody:
      "Mit dem Abo schreibst du deine eigene Fragestellung, füllst die PICO-Felder aus und prüfst eigene Strings. Das Abo gilt für alle Tools auf dieser Seite, auch für die, die noch dazukommen.",
    ctaPrimary: "Abo ansehen",
    ctaSecondary: "Anmelden",
    footnote:
      "Die Beispiele, die Begriffstabelle und das MeSH-Wörterbuch sind dieselben wie im Abo. Wörterbuch-Suche und Trefferzählung kannst du auch in der Demo nutzen, denn dafür brauchst du keine eigene Fragestellung.",
  },

  /**
   * CINAHL (EBSCOhost) and Embase (embase.com): labels for the fields the engine puts into BuiltQuery
   * (vocabulary, platform, platformNotes, limitNotes, components[].headings, lines[].suggested) and for the lint syntax picker.
   */
  databasesExtra: {
    hints: {
      cinahl: "(MH \"…+\"), TI/AB und N-Operatoren für EBSCOhost. Schlagwörter sind Vorschläge aus MeSH. Sprache, Zeitraum und Studientyp stellst du dort selbst ein.",
      embase: "'…'/exp, :ti,ab,kw und NEXT/n für embase.com. Schlagwörter sind Vorschläge aus MeSH. Sprache, Jahre und Studientyp stehen als Limits im String.",
    } as Record<string, string>,
    platforms: {
      cinahl: "EBSCOhost (CINAHL Complete)",
      embase: "embase.com (Elsevier)",
    } as Record<string, string>,
    vocabularyLabels: {
      "cinahl-headings": "CINAHL Headings",
      emtree: "Emtree",
    } as Record<string, string>,
    headings: {
      toggleLegend: "Schlagwörter",
      toggleOn: "Schlagwort-Vorschläge einschliessen",
      toggleOff: "Nur Stichworte (ohne Schlagwörter)",
      toggleHint: (vocabulary: string) =>
        `Die Schlagwörter für ${vocabulary} leitet das Tool aus MeSH ab. Der Thesaurus der Datenbank ist lizenziert, das Tool kennt ihn nicht. Schalte sie aus, wenn du nur mit Stichworten suchen willst.`,
      badge: "Vorschlag aus MeSH",
      badgeTitle: (vocabulary: string) => `Schlagwort-Vorschlag aus MeSH, im Thesaurus der Datenbank prüfen (${vocabulary})`,
      checkNote: (vocabulary: string) => `Schlagwort-Vorschlag aus MeSH. Im Thesaurus der Datenbank prüfen (${vocabulary}).`,
      columnTitle: (vocabulary: string) => `Schlagwörter (${vocabulary}, Vorschläge)`,
      offNote: "Dieser String enthält keine Schlagwörter, nur Stichworte.",
    },
    platformHeading: "So gibst du den String ein",
    limitNotesHeading: (db: string) => `Das stellst du in ${db} selbst ein`,
    lines: {
      cinahl: "Zeilenweise (S1, S2 …)",
      embase: "Zeilenweise (#1, #2 …)",
      single: "Eine Zeile",
    } as Record<string, string>,
    lint: {
      syntaxLabels: {
        cinahl: "CINAHL (EBSCOhost)",
        embase: "Embase (embase.com)",
      } as Record<string, string>,
      detected: (label: string) => `Erkannt: ${label}`,
      ovidNote:
        "Embase über Ovid hat eine andere Syntax (exp …/, .ti,ab.). Sie wird erkannt, aber nicht geprüft.",
    },
    convert: {
      toCinahl: "In CINAHL-Syntax umwandeln",
      toEmbase: "In Embase-Syntax umwandeln",
      pubmedOnly: "Umgewandelt werden nur PubMed-Strings.",
    },
  },

  paywall: {
    title: "Suchstring-Generator",
    sub: "Mit dem Abo freigeschaltet.",
    lede: "Fall einfügen, fertigen Suchstring erhalten und bei Bedarf anpassen.",
    whatHeading: "Was das Tool macht",
    points: [
      "Verarbeitet ganze Fälle und Aufgabenblätter: erkennt «P:»-Zeilen, überliest Arbeitsaufträge und schlägt Alter und Geschlecht als Filter vor, die du selbst einschaltest.",
      "Erkennt Suchkomponenten in deutschen und englischen Fragen, auch wenn du «Rueckenschmerzen» statt «Rückenschmerzen» schreibst. Zusammengesetzte Wörter wie «Schultertraining» zerlegt es in zwei Komponenten und sagt dir das.",
      "Kennt rund 17'000 MeSH-Schlagworte (MeSH 2026), nicht nur eine kleine Begriffstabelle. Deutsche Bezeichnungen gibt es für etwa die Hälfte davon, aus Wikidata und einer eigenen Liste; die übrigen findest du über den englischen Namen. Im Wörterbuch kannst du von Hand stöbern und breiter oder enger gehen.",
      "Zeigt zu jeder Komponente Schlagworte (MeSH) und Stichworte, die du entfernen, ergänzen, trunkieren oder in einen anderen Block verschieben kannst. Bei mehrdeutigen Wörtern schaltest du auf ein anderes Schlagwort um.",
      "Setzt Klammern, Field Tags und Trunkierung so, wie es die aktuelle PubMed-Hilfe vorgibt.",
      "Schreibt denselben Suchstring auch für die Cochrane Library (CENTRAL): [mh …] für Schlagworte, :ti,ab,kw für Stichworte und NEXT statt Stern in Anführungszeichen, wahlweise in einer Zeile oder zeilenweise für den Search Manager. Sprache, Zeitraum und Studientyp lassen sich dort nicht zuverlässig als Syntax schreiben. Das Tool sagt dir, was du unter «Search limits» selbst einstellst, statt Syntax zu erfinden.",
      "Zählt auf Wunsch die Treffer in PubMed, Komponente für Komponente, und sagt dir bei null oder sehr vielen Treffern, wo du lockern oder eingrenzen kannst. Für die Cochrane Library gibt es keine Trefferzählung; dort zeigt dir der Search Manager die Zahl je Zeile.",
      "Prüft eigene Strings auf typische Fehler, für PubMed und für die Cochrane Library: typografische Anführungszeichen, fehlende Klammern bei AND und OR, fehlende Field Tags oder Feldcodes, falsche Zeilenbezüge im Search Manager. Vieles davon korrigiert es mit einem Klick.",
      "Wandelt einen eingefügten String zwischen PubMed- und Cochrane-Syntax um, soweit das eindeutig geht, und listet auf, was es nicht übertragen konnte.",
    ],
    sampleHeading: "So sieht ein Ergebnis aus",
    sampleCaption: "Beispiel: der ganze Fall von Herrn Müller (OST Übung 3), erzeugt mit diesem Tool. Ein Entwurf, kein fertiger String.",
    sampleLoading: "Beispiel wird berechnet",
    privacy: "Deine Fragestellung bleibt auf deinem Gerät. Das Tool lädt nur Teile eines öffentlichen MeSH-Wörterbuchs von physio.sweber.dev nach, nie deinen Text. Die Trefferzählung ist optional und schickt nur den fertigen String an PubMed.",
    demoLink: "Kostenlose Demo ausprobieren",
    aboLink: "Abo ansehen",
    loginLink: "Anmelden",
    loginHint: "Schon ein Abo? Dann melde dich an.",
    verifyHint: "Du bist angemeldet, hast aber noch kein aktives Abo.",
  },
} as const
