/**
 * Strings of the Suchstring-Generator (tool, demo and paywall page).
 * German, Swiss orthography, informal "du". A copywriter pass happens later:
 * change wording here, not in the components.
 */
import type { Block, LintSeverity, NoticeSeverity } from "@/lib/physio/search-string/types"

export const ssCopy = {
  name: "Suchstring-Generator",
  metaTitle: "Suchstring-Generator für PubMed",
  metaDescription:
    "Baut aus deiner PICO-Frage oder deinem Patientenfall einen PubMed-Suchstring mit Schlagworten (MeSH), Stichworten, Klammern und Trunkierung. Regelbasiert, ohne KI. Deine Fragestellung bleibt auf deinem Gerät.",

  hero: {
    title: "Suchstring-Generator",
    sub: "Von der PICO-Frage zum PubMed-Suchstring.",
    lede: "Schreib deine Fragestellung rein, oder gleich den ganzen Fall. Das Tool erkennt die Suchkomponenten, schlägt Schlagworte (MeSH) und Stichworte vor und baut daraus einen String mit Klammern, Field Tags und Trunkierung. Du gehst drüber und korrigierst, bevor du kopierst.",
    demoBadge: "Demo",
    demoLede:
      "In der Demo arbeitest du mit festen Beispielen, darunter dem ganzen Fall von Herrn Müller. Komponenten und Begriffe kannst du bearbeiten, im MeSH-Wörterbuch stöbern, Treffer in PubMed zählen, den String kopieren und den Prüfmodus am Beispielstring testen.",
  },

  privacy:
    "Deine Fragestellung bleibt auf deinem Gerät. Das Tool lädt nur Teile eines öffentlichen MeSH-Wörterbuchs von physio.sweber.dev nach; abgefragt wird dabei ein Dateiname wie «terms/lo.json», nie dein Text. Die Trefferzählung ist optional und schickt nur den fertigen Suchstring an PubMed (NCBI).",
  attribution: {
    source: "MeSH: U.S. National Library of Medicine · Deutsche Bezeichnungen: Wikidata (CC0)",
    version: (version: string, descriptors: number, german: number) =>
      `Wörterbuch: MeSH ${version}, ${descriptors.toLocaleString("de-CH")} Schlagworte, davon ${german.toLocaleString("de-CH")} mit deutschen Bezeichnungen.`,
    loading: "Wörterbuch wird geladen",
  },
  glossary: [
    { term: "Suchkomponente", text: "ein Baustein deiner Frage, zum Beispiel «Rückenschmerzen». Im String ist das eine Klammer, in der die Begriffe mit OR verknüpft sind." },
    { term: "Stichwort", text: "ein Freitext-Begriff, den PubMed in Titel und Abstract sucht ([tiab])." },
    { term: "Schlagwort", text: "ein MeSH-Term aus dem kontrollierten Vokabular von PubMed ([Mesh])." },
  ],

  draftNote: {
    title: "Das ist ein Entwurf.",
    body: "Geh Begriffe und Schlagworte durch und schau dir die Trefferliste an, bevor du den String in einer Arbeit verwendest. Das Tool arbeitet mit festen Regeln, dem MeSH-Wörterbuch und einer eigenen Begriffstabelle. Wie es deutsche Wörter den Schlagworten zuordnet, ist fachlich noch nicht geprüft.",
  },

  tabs: { generate: "Suchstring erstellen", lint: "Eigenen String prüfen" },

  step: { label: "Schritt" },

  question: {
    heading: "Fragestellung",
    hint: "Forschungsfrage, PICO-Frage oder der ganze Fall samt Aufgabenblatt, auf Deutsch oder Englisch. Arbeitsaufträge wie «Formulieren Sie …» überliest das Tool.",
    exampleLabel: "Beispiel laden",
    examplePlaceholder: "Beispiel wählen",
    textLabel: "Deine Fragestellung",
    textPlaceholder: "Wie wirkt Krafttraining auf die Schmerzen bei älteren Menschen mit Kniearthrose?",
    textHint:
      "Tipp: «bei» leitet die Population ein, «im Vergleich zu» den Vergleich, «auf die» das Outcome. Zeilen mit «P:», «I:», «C:», «O:» oder «Population:», «Intervention:», «Outcome:» haben Vorrang. Schreib Hauptwörter gross, dann erkennt das Tool sie sicherer.",
    analysing: "Wörterbuch wird geladen und Fragestellung ausgewertet",
    analysed: "Auswertung fertig.",
    picoSummary: "Optional: PICO-Felder einzeln ausfüllen",
    picoHint: "Was du hier einträgst, landet fix im passenden Block.",
    pico: {
      population: { label: "Population (P)", placeholder: "Wer? Person oder Erkrankung" },
      intervention: { label: "Intervention (I)", placeholder: "Was wird gemacht?" },
      comparison: { label: "Vergleich (C)", placeholder: "Womit wird verglichen?" },
      outcome: { label: "Outcome (O)", placeholder: "Was wird gemessen?" },
      studyType: { label: "Studientyp", placeholder: "zum Beispiel RCT" },
    },
    submit: "Suchstring erstellen",
    submitting: "Wird ausgewertet",
    reset: "Zurücksetzen",
    emptyError: "Schreib zuerst eine Fragestellung oder füll mindestens ein PICO-Feld aus.",
    failError: "Die Fragestellung liess sich nicht auswerten. Kürze den Text oder füll die PICO-Felder direkt aus.",
    lockedTitle: "In der Demo kannst du nur die Beispiele wählen.",
    lockedBody: "Eigene Fragestellungen und PICO-Felder gibt es mit dem Abo.",
    editedHint: "«Suchstring erstellen» setzt deine Änderungen an den Komponenten zurück.",
  },

  concepts: {
    heading: "Erkannte Suchkomponenten",
    hint: "Schau nach, ob das Tool deine Frage richtig verstanden hat. Entferne, verschiebe oder ergänze Komponenten, bevor du den String übernimmst.",
    emptyTitle: "Noch keine Suchkomponente.",
    emptyBody: "Erstelle den String im ersten Schritt oder füge unten eine Komponente hinzu.",
    waiting: "Der Rest erscheint, sobald du im ersten Schritt auf «Suchstring erstellen» klickst.",
    detectedFrom: "erkannt aus",
    custom: "eigene Komponente",
    noMesh: "Kein Schlagwort hinterlegt. Diese Komponente wird nur über Stichworte gesucht.",
    blocks: {
      population: { title: "Population", sub: "Wer oder welche Erkrankung?" },
      intervention: { title: "Intervention", sub: "Was wird gemacht?" },
      comparison: { title: "Vergleich", sub: "Womit wird verglichen?" },
      outcome: { title: "Outcome", sub: "Was wird gemessen?" },
    } satisfies Record<Block, { title: string; sub: string }>,
    blockInclude: "Im Suchstring",
    blockExcluded: "Dieser Block steht nicht im String.",
    comparisonNote: "Ein Vergleich im String schränkt die Treffer meist zu stark ein. Darum ist dieser Block standardmässig aus.",
    emptyBlock: "Keine Komponente in diesem Block.",
    schlagworte: "Schlagworte (MeSH)",
    stichworte: "Stichworte",
    explodeOn: "mit Unterbegriffen",
    explodeOff: "ohne Unterbegriffe",
    explodeHelp: "Mit Unterbegriffen findet [Mesh] auch alle engeren MeSH-Terms darunter. Ohne ([Mesh:NoExp]) nur genau diesen einen.",
    removeConcept: "Komponente entfernen",
    removeConceptButton: "Entfernen",
    allMeshRemoved: "Alle Schlagworte sind entfernt.",
    allTextRemoved: "Alle Stichworte sind entfernt.",
    moveTo: "Block",
    removeTerm: "entfernen",
    restore: "Wiederherstellen",
    removedTerms: "Entfernte Begriffe",
    addTermLabel: "Stichwort ergänzen",
    addTermPlaceholder: "englisches Wort oder Phrase",
    addTermButton: "Hinzufügen",
    addTermHint: "PubMed sucht auf Englisch. Mit * trunkierst du: exercis* findet exercise, exercises und exercising.",
    addConceptHeading: "Komponente ergänzen",
    addFromList: "Aus der Begriffstabelle",
    addFromListPlaceholder: "Komponente wählen",
    addFromListButton: "Komponente hinzufügen",
    addCustomLabel: "Eigene Komponente",
    addCustomPlaceholder: "englisches Stichwort",
    addCustomButton: "Eigene Komponente hinzufügen",
    categories: {
      population: "Population und Erkrankung",
      setting: "Umfeld",
      intervention: "Intervention",
      comparison: "Vergleich",
      outcome: "Outcome",
      studytype: "Studientyp",
    },
    candidatesHeading: "Nicht übernommene Wörter",
    candidatesHint:
      "Diese Wörter hat das Tool nicht als Komponente aufgenommen. Bei manchen kennt das MeSH-Wörterbuch einen Begriff, der aber zu allgemein ist, um ihn ungefragt zu übernehmen. Alle anderen kannst du als Stichwort übernehmen, dann aber auf Englisch, weil PubMed so sucht.",
    candidateSuggestion: "Im Wörterbuch",
    candidateAddSuggestion: "Als Komponente übernehmen",
    candidateAdd: "Als Stichwort übernehmen",
    candidateDismiss: "Verwerfen",
    candidateBlock: "Block",
    notices: "Hinweise zur Auswertung",
    meshTitle: "Definition und deutsche Bezeichnungen",
    englishName: "Englisch",
    scopeNote: "Definition (englisch)",
    germanNames: "Deutsche Bezeichnungen",
    noGerman: "Keine deutsche Bezeichnung im Wörterbuch.",
    alternativesHeading: "Anderes Schlagwort wählen",
    alternativesHint: "Das Wort kann mehrere Schlagworte meinen. Das Tool hat das für Physiotherapie naheliegendste gewählt. Passt ein anderes besser, schalte um.",
    alternativesUse: "Dieses nehmen",
    moreSynonyms: "Weitere Synonyme aus MeSH",
    moreSynonymsHint: "Ein Klick nimmt das Synonym als Stichwort auf.",
    truncOn: "mit *",
    truncOff: "ohne *",
    truncHelp: "Stern anhängen: exercise* findet auch exercises und exercising. Das hilft nur, wenn der Wortanfang eindeutig ist.",
    truncLabel: "Trunkierung",
    tree: {
      open: "Breiter oder enger",
      close: "Schliessen",
      heading: "Breiter oder enger suchen",
      hint: "Ein breiteres Schlagwort findet mehr, ein engeres weniger. Mit «mit Unterbegriffen» sucht [Mesh] ohnehin alles darunter.",
      broader: "Breiter",
      narrower: "Enger",
      noBroader: "Das ist schon der oberste Begriff in diesem Zweig.",
      noNarrower: "Keine engeren Begriffe.",
      use: "Ersetzen durch",
      loading: "Wörterbuch wird geladen",
      failed: "Der Begriff liess sich im Wörterbuch nicht finden.",
    },
  },

  mesh: {
    heading: "MeSH-Wörterbuch durchsuchen",
    hint: "Such ein Schlagwort auf Deutsch oder Englisch, lies die Definition und nimm es als Komponente auf. Ab drei Buchstaben erscheinen Vorschläge. Deutsche Bezeichnungen gibt es für etwa die Hälfte der Schlagworte; findest du nichts, probier den englischen Namen.",
    label: "Schlagwort suchen",
    placeholder: "zum Beispiel Rückenschmerzen oder low back pain",
    loading: "Wörterbuch wird geladen",
    minChars: "Tippe mindestens drei Buchstaben.",
    noResults: "Keine Treffer. Probier den englischen Namen oder einen kürzeren Wortanfang.",
    failed: "Das Wörterbuch ist gerade nicht erreichbar. Versuch es später noch einmal.",
    results: (n: number) => `${n} ${n === 1 ? "Vorschlag" : "Vorschläge"}`,
    english: "Englisch",
    german: "Deutsch",
    noGerman: "keine deutsche Bezeichnung",
    category: "Bereich",
    treeNumbers: "Baumnummer",
    scopeNote: "Definition (englisch)",
    noScopeNote: "Keine Definition im Wörterbuch.",
    broader: "Breiter",
    narrower: "Enger",
    noBroader: "oberster Begriff",
    noNarrower: "keine engeren Begriffe",
    add: "Zu Suchkomponente hinzufügen",
    addBlock: "Block",
    added: "Hinzugefügt. Du findest die Komponente oben im gewählten Block.",
    alreadyThere: "Diese Komponente gibt es schon.",
    categories: {
      A: "Körperregion und Anatomie",
      B: "Lebewesen",
      C: "Krankheit oder Beschwerde",
      D: "Medikament oder Substanz",
      E: "Verfahren und Geräte",
      F: "Psyche und Verhalten",
      G: "Körperfunktion und Vorgänge",
      H: "Fachgebiet",
      I: "Gesellschaft und Bildung",
      J: "Technik und Ernährung",
      L: "Information",
      M: "Personengruppe",
      N: "Gesundheitswesen",
      V: "Publikationstyp",
      Z: "Ort",
    } as Record<string, string>,
  },

  database: {
    heading: "Datenbank und Filter",
    hint: "In dieser Version gibt es nur PubMed. Weitere Datenbanken kommen später.",
    legend: "Datenbank",
    soon: "bald",
    filtersHeading: "Filter",
    filtersHint: "Alle Filter sind optional.",
    language: "Sprache",
    languageAny: "alle Sprachen",
    years: "Erscheinungsjahr",
    yearFrom: "von",
    yearTo: "bis",
    yearPlaceholder: "Jahr",
    studyTypes: "Studientyp",
    studyTypeLabels: {
      rct: "Randomisierte kontrollierte Studie",
      "systematic-review": "Systematische Übersichtsarbeit",
      "meta-analysis": "Metaanalyse",
    },
    humans: "Nur Studien am Menschen",
    humansHint: "Schliesst reine Tierstudien aus.",
    caseHeading: "Vorschläge aus deinem Fall",
    caseHint:
      "Alter und Geschlecht stehen oft im Fall. Als Filter schränken sie die Treffer stark ein, weil PubMed beides nicht bei jeder Studie verschlagwortet. Darum sind die Vorschläge aus. Schalte sie nur ein, wenn die Frage wirklich auf diese Gruppe zielt.",
    fromCase: (evidence: string) => `aus «${evidence}»`,
    ageLabels: {
      "Infant, Newborn": "Neugeborene",
      Infant: "Säuglinge (bis 23 Monate)",
      "Child, Preschool": "Vorschulkinder (2 bis 5 Jahre)",
      Child: "Kinder (6 bis 12 Jahre)",
      Adolescent: "Jugendliche (13 bis 18 Jahre)",
      "Young Adult": "Junge Erwachsene (19 bis 24 Jahre)",
      Adult: "Erwachsene (19 bis 44 Jahre)",
      "Middle Aged": "Mittleres Alter (45 bis 64 Jahre)",
      Aged: "Ältere (65 bis 79 Jahre)",
      "Aged, 80 and over": "Hochbetagte (ab 80 Jahren)",
    } as Record<string, string>,
    sexLabels: { Male: "Männlich", Female: "Weiblich" } as Record<string, string>,
  },

  result: {
    heading: "Suchstring",
    hint: "Kopiere den String direkt ins Suchfeld von PubMed oder lade ihn herunter.",
    stringLabel: "Suchstring für PubMed",
    empty: "Noch kein Suchstring. Dafür braucht es mindestens eine Suchkomponente mit einem aktiven Begriff.",
    copy: "Kopieren",
    copied: "Kopiert",
    copyFailed: "Kopieren hat nicht geklappt. Markiere den String und kopiere ihn von Hand.",
    downloadTxt: "Als .txt",
    downloadJson: "Als .json",
    stats: (components: number, terms: number) =>
      `${components} ${components === 1 ? "Suchkomponente" : "Suchkomponenten"}, ${terms} ${terms === 1 ? "Begriff" : "Begriffe"}`,
    noticesHeading: "Auf einen Blick",
    tableHeading: "Suchkomponenten im Überblick",
    tableCols: { component: "Suchkomponente", keywords: "Stichworte", subjectHeadings: "Schlagworte (MeSH)" },
    none: "keine",
    legend: "So liest du den String: Schlagworte mit [Mesh] sind umrandet, Stichworte mit [tiab] sucht PubMed in Titel und Abstract, AND und OR sind grau.",
  },

  pubmed: {
    heading: "Treffer in PubMed",
    hint: "Optional. Zählt die Treffer jeder Suchkomponente und des ganzen Strings, damit du siehst, welche Komponente die Suche zu stark einschränkt.",
    privacy: "Dafür sendet dein Browser den Suchstring (nicht deine Fragestellung) an PubMed beim US-amerikanischen NCBI.",
    count: "Treffer in PubMed zählen",
    recount: "Noch einmal zählen",
    counting: (done: number, total: number) => `Zähle … (${done} von ${total})`,
    cancel: "Abbrechen",
    cancelled: "Abgebrochen. Die bisherigen Zahlen stehen unten.",
    open: "In PubMed öffnen",
    colComponent: "Suchkomponente",
    colHits: "Treffer",
    total: "Ganzer String",
    pending: "ausstehend",
    failedRow: "Fehler",
    errors: {
      rate: "PubMed hat die Anfragen vorübergehend begrenzt. Warte eine Minute und zähle noch einmal.",
      network: "PubMed ist von deinem Browser aus gerade nicht erreichbar. Prüfe die Verbindung oder öffne den String direkt in PubMed.",
      query: "PubMed hat den String nicht verstanden. Öffne ihn in PubMed, dort steht, was nicht stimmt.",
      other: "Die Zählung hat nicht geklappt. Öffne den String direkt in PubMed.",
    },
    zeroTotal:
      "Der ganze String findet nichts. Schau in der Tabelle, welche Komponente die wenigsten Treffer hat, und lockere dort zuerst. Was meist hilft: eine Komponente rausnehmen (drei bis vier reichen in der Regel), den String einmal ohne den Block Population probieren, ein enges Schlagwort über «Breiter oder enger» durch ein breiteres ersetzen, und die Trunkierung prüfen: Ein Stichwort ohne * findet nur genau diese Wortform.",
    fewTotal:
      "Der ganze String findet nur wenige Treffer. Lockere zuerst die Komponente mit den wenigsten Treffern: ein breiteres Schlagwort, «mit Unterbegriffen» einschalten oder ein Synonym mehr als Stichwort.",
    manyTotal:
      "Der ganze String findet sehr viele Treffer. Eine engere Population, ein konkretes Outcome oder ein Studientyp-Filter grenzt ein.",
    number: (n: number) => n.toLocaleString("de-CH"),
  },

  severity: {
    info: "Hinweis",
    warning: "Warnung",
    error: "Fehler",
  } satisfies Record<NoticeSeverity | LintSeverity, string>,

  lint: {
    heading: "Eigenen String prüfen",
    hint: "Füge deinen PubMed-Suchstring ein, zum Beispiel aus einer Übung. Das Tool markiert typische Fehler wie typografische Anführungszeichen, fehlende Klammern bei AND und OR oder fehlende Field Tags, und korrigiert, wo es geht.",
    inputLabel: "Dein Suchstring",
    inputPlaceholder: '("back pain"[tiab] OR "Back Pain"[Mesh]) AND ...',
    lockedTitle: "In der Demo kannst du nur den Beispielstring prüfen.",
    lockedBody: "Eigene Strings prüfst du mit dem Abo. Die Korrekturen kannst du hier schon ausprobieren.",
    insertExample: "Beispielstring einfügen",
    resetExample: "Beispielstring zurücksetzen",
    clear: "Leeren",
    undo: "Rückgängig",
    markedHeading: "Markierte Stellen",
    emptyTitle: "Noch kein String.",
    emptyBody: "Füge oben einen Suchstring ein. Die Prüfung läuft beim Tippen mit.",
    cleanTitle: "Nichts gefunden.",
    cleanBody: "Die Syntax stimmt. Ob die Begriffe zu deiner Frage passen, kann das Tool nicht beurteilen, das bleibt bei dir.",
    summary: (errors: number, warnings: number, infos: number) => {
      const parts: string[] = []
      if (errors) parts.push(`${errors} Fehler`)
      if (warnings) parts.push(`${warnings} ${warnings === 1 ? "Warnung" : "Warnungen"}`)
      if (infos) parts.push(`${infos} ${infos === 1 ? "Hinweis" : "Hinweise"}`)
      return parts.join(", ")
    },
    goTo: "Zur Stelle",
    fix: "Korrigieren",
    fixAll: "Alles automatisch korrigieren",
    fixAllDone: (n: number) => `${n} ${n === 1 ? "Korrektur" : "Korrekturen"} angewendet.`,
    fixAllNone: "Hier gibt es nichts, was sich automatisch korrigieren lässt.",
    at: "Stelle",
    moreSpots: (n: number) => `und ${n} weitere ${n === 1 ? "Stelle" : "Stellen"}`,
  },

  demo: {
    ctaHeading: "Eigene Fragen auswerten",
    ctaBody:
      "Mit dem Abo schreibst du deine eigene Fragestellung, füllst die PICO-Felder aus und prüfst eigene Strings. Das Abo gilt für alle Tools auf dieser Seite, auch für die, die noch dazukommen.",
    ctaPrimary: "Abo ansehen",
    ctaSecondary: "Anmelden",
    footnote:
      "Die Beispiele, die Begriffstabelle und das MeSH-Wörterbuch sind dieselben wie im Abo. Wörterbuch-Suche und Trefferzählung kannst du auch in der Demo nutzen, denn dafür brauchst du keine eigene Fragestellung.",
  },

  paywall: {
    title: "Suchstring-Generator",
    sub: "Mit dem Abo freigeschaltet.",
    lede: "Du schreibst deine PICO-Frage oder die Aufgabe aus dem Unterricht rein. Das Tool erkennt die Suchkomponenten, ordnet Schlagworte (MeSH) und Stichworte zu und baut daraus einen PubMed-String. Du gehst drüber und korrigierst, bevor du ihn kopierst.",
    whatHeading: "Was das Tool macht",
    points: [
      "Verarbeitet ganze Fälle und Aufgabenblätter: erkennt «P:»-Zeilen, überliest Arbeitsaufträge und schlägt Alter und Geschlecht als Filter vor, die du selbst einschaltest.",
      "Erkennt Suchkomponenten in deutschen und englischen Fragen, auch wenn du «Rueckenschmerzen» statt «Rückenschmerzen» schreibst. Zusammengesetzte Wörter wie «Schultertraining» zerlegt es in zwei Komponenten und sagt dir das.",
      "Kennt rund 17'000 MeSH-Schlagworte (MeSH 2026), nicht nur eine kleine Begriffstabelle. Deutsche Bezeichnungen gibt es für etwa die Hälfte davon, aus Wikidata und einer eigenen Liste; die übrigen findest du über den englischen Namen. Im Wörterbuch kannst du von Hand stöbern und breiter oder enger gehen.",
      "Zeigt zu jeder Komponente Schlagworte (MeSH) und Stichworte, die du entfernen, ergänzen, trunkieren oder in einen anderen Block verschieben kannst. Bei mehrdeutigen Wörtern schaltest du auf ein anderes Schlagwort um.",
      "Setzt Klammern, Field Tags und Trunkierung so, wie es die aktuelle PubMed-Hilfe vorgibt.",
      "Zählt auf Wunsch die Treffer in PubMed, Komponente für Komponente, und sagt dir bei null oder sehr vielen Treffern, wo du lockern oder eingrenzen kannst.",
      "Prüft eigene Strings auf typische Fehler: typografische Anführungszeichen, fehlende Klammern bei AND und OR, fehlende Field Tags. Vieles davon korrigiert es mit einem Klick.",
    ],
    sampleHeading: "So sieht ein Ergebnis aus",
    sampleCaption: "Beispiel: der ganze Fall von Herrn Müller (OST Übung 3), erzeugt mit diesem Tool. Ein Entwurf, kein fertiger String.",
    sampleLoading: "Beispiel wird berechnet",
    privacy: "Deine Fragestellung bleibt auf deinem Gerät. Das Tool lädt nur Teile eines öffentlichen MeSH-Wörterbuchs von physio.sweber.dev nach, nie deinen Text. Die Trefferzählung ist optional und schickt nur den fertigen String an PubMed.",
    demoLink: "Kostenlose Demo ausprobieren",
    aboLink: "Abo ansehen",
    loginLink: "Anmelden",
    loginHint: "Schon ein Abo? Dann melde dich an.",
    verifyHint: "Du bist angemeldet, hast aber noch kein aktives Abo.",
  },
} as const
