// Monotonic ULIDs: 48-bit millisecond timestamp + 80 random bits, Crockford base32.
// Within the same millisecond the random part is incremented, so ids generated by one process
// sort in the order they were created.

const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

let lastTime = -1;
let lastRandom: number[] = [];

function randomDigits(): number[] {
  const bytes = new Uint8Array(16);
  globalThis.crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b % 32);
}

function increment(digits: number[]): number[] {
  const next = [...digits];
  for (let i = next.length - 1; i >= 0; i--) {
    if ((next[i] as number) < 31) {
      next[i] = (next[i] as number) + 1;
      return next;
    }
    next[i] = 0;
  }
  // 80 bits exhausted within one millisecond: practically impossible, start over randomly.
  return randomDigits();
}

function encodeTime(time: number): string {
  let out = "";
  let t = time;
  for (let i = 0; i < 10; i++) {
    out = ALPHABET[t % 32] + out;
    t = Math.floor(t / 32);
  }
  return out;
}

/** Creates a ULID for the given time (default now). */
export function ulid(time: number = Date.now()): string {
  if (time <= lastTime) {
    lastRandom = increment(lastRandom);
    time = lastTime;
  } else {
    lastTime = time;
    lastRandom = randomDigits();
  }
  return encodeTime(time) + lastRandom.map((d) => ALPHABET[d]).join("");
}
